import Head from 'next/head'
import { Card, Container, HStack, ScrollView, SolidButton, Text, VStack } from '@/components';
import { useMemo } from 'react';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();

  const renderWelcomeCard = useMemo(() => { 
    return (
      <Card header={'Hello!'}>
        <VStack space={'24px'}>
          <Text>Please choose one of the games listed<br/> on the Project Readme.</Text>
          <HStack space={'24px'} alignItems={'center'} width={'100%'}>
            <SolidButton label={'MLB'} flex={'0.5'} backgroundColor={'blue'} animateHover onClick={() => {router.push('game/eed38457-db28-4658-ae4f-4d4d38e9e212')}}></SolidButton>
            <SolidButton label={'NBA'} flex={'0.5'} backgroundColor={'red'} animateHover onClick={() => {router.push('game/6c974274-4bfc-4af8-a9c4-8b926637ba74')}}></SolidButton>
          </HStack>
          {/* <Text marginBottom={'24px'}>Alternatively, please type the UUID<br/> of the game you would like to view below.</Text>
          <HStack space={'24px'} alignItems={'center'} width={'100%'}>
            <TextInput label={'Search Value'} flex={'0.5'}></TextInput>
            <SolidButton label={'Go'} backgroundColor={'green'} animateHover></SolidButton>
          </HStack> */}
        </VStack>
      </Card>
    )
  }, [router])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <ScrollView padding={'40px'} width={'100%'}>
            <VStack space={'40px'} width={'100%'} alignItems={'center'}>
              {renderWelcomeCard}
            </VStack>
          </ScrollView>
        </Container>
      </main>
    </>
  )
}
